chore: update release workflow to improve versioning and publishing process

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,7 +9,6 @@ concurrency: ${{ github.workflow }}-${{ github.ref }}
 
 permissions:
   contents: write
-  pull-requests: write
 
 jobs:
   release:
@@ -18,19 +17,14 @@ jobs:
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Setup Node.js 20
         uses: actions/setup-node@v4
         with:
           node-version: 20
-
-      - name: Cache Dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.pnpm-store
-          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-
 
       - name: Setup pnpm
         uses: pnpm/action-setup@v3
@@ -38,19 +32,42 @@ jobs:
           version: 8
 
       - name: Install Dependencies
-        run: pnpm install --no-frozen-lockfile
-        working-directory: packages/stark-ui
+        run: pnpm install --frozen-lockfile
 
       - name: Build packages
         run: pnpm build
 
-      - name: Create Release Pull Request or Publish to npm
-        uses: changesets/action@v1
-        with:
-          title: '[Chore] version packages'
-          commit: 'chore: version packages'
-          version: pnpm changeset version
-          publish: pnpm changeset publish
+      - name: Configure Git
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Version packages
+        id: version
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Working directory is not clean. Aborting."
+            exit 1
+          fi
+
+          pnpm changeset version
+
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "changes_exist=true" >> $GITHUB_ENV
+          else
+            echo "changes_exist=false" >> $GITHUB_ENV
+          fi
+
+      - name: Commit and push version changes
+        if: env.changes_exist == 'true'
+        run: |
+          git add .
+          git commit -m "chore: version packages [skip ci]"
+          git push
+
+      - name: Publish to npm
+        if: env.changes_exist == 'true'
+        run: pnpm changeset publish
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
